# Config File

gtf_file:
  /home/groups/hoolock2/u0/genomes/ensembl/mus_musculus/annotation/Mus_musculus.GRCm38.99.gtf

bismark_ref_genome:
  /home/groups/hoolock2/u0/genomes/ensembl/mus_musculus

metadata_file:
  "metadata.txt"

group_var:
  "Group" # colname of metadata file to define groups

min_cov:
  1 # minimum cov for cpg's during object read-in

min_cov_merge:
  10 # minimum cov for merging samples (common first attempt is 10 or 5)

perc_merge:
  99.9 # high percentage cov cutoff for merging samples

merge_regional:
  FALSE # whether to merge on cpg-level (FALSE) or merge tiles (TRUE)

min_cpg_region:
  10 # if merging regions, minimum number of covered CpGs required in the region to retain it

mpg:
  "NULL" # min per group parameter for merging, NULL means all samples

merge_dirname:
  "merged_mincov_10_allsamps"

repeat_initial_ide:
  FALSE # when running IDE the first time, want to set as TRUE. When repeating merging, set to FALSE

